version: '3'

vars:
  APP_NAME: rewind
  BIN_DIR: bin
  VITE_PORT: 5173

tasks:
  dev:
    desc: Run the application in development mode
    deps: [build:frontend]
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  dev:frontend:
    desc: Run frontend dev server (standalone)
    dir: frontend
    env:
      VITE_PORT: "{{.VITE_PORT}}"
    cmds:
      - npm run dev

  dev:backend:
    desc: Run Go backend only (requires frontend build)
    deps: [install:frontend, build:frontend]
    cmds:
      - go run .

  windows:build:
    desc: Build the Windows application
    deps: [build:frontend]
    cmds:
      - powershell -Command "if (!(Test-Path .build)) { mkdir .build | Out-Null }"
      - go build -ldflags="-w -s -H windowsgui" -o .build/{{.APP_NAME}}.exe .

  install:frontend:
    desc: Install frontend dependencies
    dir: frontend
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/**/*
    cmds:
      - npm install

  build:frontend:
    desc: Build the frontend
    deps: [install:frontend]
    dir: frontend
    sources:
      - src/**/*
      - index.html
      - vite.config.ts
      - package.json
    generates:
      - dist/**/*
    cmds:
      - npm run build

  build:installer:
    desc: Build NSIS installer (requires NSIS installed)
    deps: [windows:build]
    dir: .
    platforms: [windows]
    cmds:
      - powershell -Command "if (!(Test-Path .build/bin)) { mkdir .build/bin | Out-Null }"
      - powershell -Command "Copy-Item bin\ffmpeg.exe .build\bin\ffmpeg.exe -Force"
      - powershell -Command "Copy-Item build\installer.nsi .build\installer.nsi -Force"
      - makensis .build/installer.nsi

  build:portable:
    desc: Build portable ZIP archive
    deps: [windows:build]
    dir: .
    platforms: [windows]
    cmds:
      - powershell -Command "if (!(Test-Path .build/bin)) { mkdir .build/bin | Out-Null }"
      - powershell -Command "Copy-Item bin\ffmpeg.exe .build\bin\ffmpeg.exe -Force"
      - powershell -Command "Compress-Archive -Path .build\rewind.exe,.build\bin -DestinationPath .build\Rewind-Portable.zip -Force"

  package:
    desc: Build executable + installer + portable ZIP
    cmds:
      - task: build:installer
      - task: build:portable

  clean:
    desc: Clean build artifacts
    cmds:
      - powershell -Command "if (Test-Path .build) { Remove-Item -Recurse -Force .build }"
      - powershell -Command "if (Test-Path frontend/dist) { Remove-Item -Recurse -Force frontend/dist }"
