// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service for Wails binding
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConvertToMP4 converts a .ts clip to .mp4 and deletes the original .ts file
 * @param {string} inputPath
 * @returns {$CancellablePromise<void>}
 */
export function ConvertToMP4(inputPath) {
    return $Call.ByID(2494522454, inputPath);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function EmitClipsUpdate() {
    return $Call.ByID(1742949134);
}

/**
 * EstimateMemory calculates the estimated buffer size based on bitrate and duration
 * @param {string} bitrate
 * @param {number} seconds
 * @returns {$CancellablePromise<string>}
 */
export function EstimateMemory(bitrate, seconds) {
    return $Call.ByID(2746090786, bitrate, seconds);
}

/**
 * GetClips returns a list of saved clips in the output directory.
 * @returns {$CancellablePromise<$models.Clip[]>}
 */
export function GetClips() {
    return $Call.ByID(1177836312).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConfig returns the current configuration
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(54167495).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetDisplays returns all available displays
 * @returns {$CancellablePromise<$models.DisplayInfo[]>}
 */
export function GetDisplays() {
    return $Call.ByID(2865430162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetEncodersForDisplay returns available encoders for a specific display
 * @param {number} displayIndex
 * @returns {$CancellablePromise<$models.EncoderInfo[]>}
 */
export function GetEncodersForDisplay(displayIndex) {
    return $Call.ByID(2664662971, displayIndex).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetState returns the current state
 * @returns {$CancellablePromise<$models.State>}
 */
export function GetState() {
    return $Call.ByID(1908551158).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Initialize detects hardware and prepares the app
 * @returns {$CancellablePromise<void>}
 */
export function Initialize() {
    return $Call.ByID(1892792513);
}

/**
 * IsRecording returns true if currently recording
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRecording() {
    return $Call.ByID(3417054602);
}

/**
 * OpenClip opens a clip in the default system player
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenClip(path) {
    return $Call.ByID(212697137, path);
}

/**
 * SaveClip saves the current buffer as a clip
 * @returns {$CancellablePromise<string>}
 */
export function SaveClip() {
    return $Call.ByID(1174966320);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(4036395914);
}

/**
 * SetApp stores the Wails application instance for event emission
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3791233416, app);
}

/**
 * SetConfig updates the configuration (only when not recording)
 * @param {$models.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetConfig(cfg) {
    return $Call.ByID(1444268075, cfg);
}

/**
 * Start begins recording
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1345961481);
}

/**
 * Stop stops recording
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2046514339);
}

// Private type creation functions
const $$createType0 = $models.Clip.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Config.createFrom;
const $$createType3 = $models.DisplayInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.EncoderInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.State.createFrom;
