// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseOutputDirectory opens a directory picker dialog
 * @returns {$CancellablePromise<string>}
 */
export function ChooseOutputDirectory() {
    return $Call.ByID(785859534);
}

/**
 * DeleteClips deletes the specified clip files
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function DeleteClips(paths) {
    return $Call.ByID(338452631, paths);
}

/**
 * GetConfig returns the current configuration
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(54167495).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetRecordingState returns the current recording state
 * @returns {$CancellablePromise<$models.State>}
 */
export function GetRecordingState() {
    return $Call.ByID(2498978161).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * IsRecording returns true if currently recording
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRecording() {
    return $Call.ByID(3417054602);
}

/**
 * ListAudioInputDevices returns available microphone devices
 * @returns {$CancellablePromise<string[]>}
 */
export function ListAudioInputDevices() {
    return $Call.ByID(2973957192).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListAudioOutputDevices returns available speaker/loopback devices
 * @returns {$CancellablePromise<string[]>}
 */
export function ListAudioOutputDevices() {
    return $Call.ByID(4007188933).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListAvailableDisplays returns all available displays/monitors
 * @returns {$CancellablePromise<$models.DisplayInfo[]>}
 */
export function ListAvailableDisplays() {
    return $Call.ByID(4189349241).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListSavedClips returns a list of saved clips in the output directory
 * @returns {$CancellablePromise<$models.Clip[]>}
 */
export function ListSavedClips() {
    return $Call.ByID(971799233).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LoadConfig() {
    return $Call.ByID(2921272697);
}

/**
 * OpenClipInExplorer opens a clip in the default system player
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenClipInExplorer(path) {
    return $Call.ByID(276444365, path);
}

/**
 * OpenOutputDirectory opens the output directory in the system file explorer
 * @returns {$CancellablePromise<void>}
 */
export function OpenOutputDirectory() {
    return $Call.ByID(2470192441);
}

/**
 * SaveCurrentClip saves the replay buffer to a file
 * @returns {$CancellablePromise<string>}
 */
export function SaveCurrentClip() {
    return $Call.ByID(1473988601);
}

/**
 * SetApp stores the Wails application instance for event emission
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3791233416, app);
}

/**
 * SetOnStateChange sets a callback for tray state updates
 * @param {any} callback
 * @returns {$CancellablePromise<void>}
 */
export function SetOnStateChange(callback) {
    return $Call.ByID(2855291673, callback);
}

/**
 * StartRecording begins screen capture and replay buffer recording
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording() {
    return $Call.ByID(3539635664);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopRecording() {
    return $Call.ByID(3285276366);
}

/**
 * @param {$models.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(cfg) {
    return $Call.ByID(1042957124, cfg);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $models.State.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.DisplayInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Clip.createFrom;
const $$createType6 = $Create.Array($$createType5);
