// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Clip represents a saved video file
 */
export class Clip {
    /**
     * Creates a new Clip instance.
     * @param {Partial<Clip>} [$$source = {}] - The source object to create the Clip.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modTime"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Clip instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Clip}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Clip(/** @type {Partial<Clip>} */($$parsedSource));
    }
}

/**
 * Config represents user-configurable settings
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("displayIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["displayIndex"] = 0;
        }
        if (!("encoderName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["encoderName"] = "";
        }
        if (!("fps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fps"] = 0;
        }
        if (!("bitrate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bitrate"] = "";
        }
        if (!("recordSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["recordSeconds"] = 0;
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("convertToMP4" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["convertToMP4"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * DisplayInfo is display info for frontend
 */
export class DisplayInfo {
    /**
     * Creates a new DisplayInfo instance.
     * @param {Partial<DisplayInfo>} [$$source = {}] - The source object to create the DisplayInfo.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("isPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplayInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DisplayInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisplayInfo(/** @type {Partial<DisplayInfo>} */($$parsedSource));
    }
}

/**
 * EncoderInfo is encoder info for frontend
 */
export class EncoderInfo {
    /**
     * Creates a new EncoderInfo instance.
     * @param {Partial<EncoderInfo>} [$$source = {}] - The source object to create the EncoderInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("codec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codec"] = "";
        }
        if (!("gpuName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gpuName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncoderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EncoderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncoderInfo(/** @type {Partial<EncoderInfo>} */($$parsedSource));
    }
}

/**
 * State holds the current application state
 */
export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = undefined;
        }
        if (!("bufferUsage" in $$source)) {
            /**
             * percentage 0-100
             * @member
             * @type {number}
             */
            this["bufferUsage"] = 0;
        }
        if (!("recordingFor" in $$source)) {
            /**
             * seconds since recording started
             * @member
             * @type {number}
             */
            this["recordingFor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

/**
 * Status represents the current application state
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusIdle: "idle",
    StatusRecording: "recording",
    StatusSaving: "saving",
    StatusError: "error",
};
