// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToMP4(arg1) {
  return window['go']['app']['App']['ConvertToMP4'](arg1);
}

export function EmitClipsUpdate() {
  return window['go']['app']['App']['EmitClipsUpdate']();
}

export function EstimateMemory(arg1, arg2) {
  return window['go']['app']['App']['EstimateMemory'](arg1, arg2);
}

export function GetClips() {
  return window['go']['app']['App']['GetClips']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDisplays() {
  return window['go']['app']['App']['GetDisplays']();
}

export function GetEncoders() {
  return window['go']['app']['App']['GetEncoders']();
}

export function GetEncodersForDisplay(arg1) {
  return window['go']['app']['App']['GetEncodersForDisplay'](arg1);
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function Initialize() {
  return window['go']['app']['App']['Initialize']();
}

export function IsRecording() {
  return window['go']['app']['App']['IsRecording']();
}

export function OpenClip(arg1) {
  return window['go']['app']['App']['OpenClip'](arg1);
}

export function SaveClip() {
  return window['go']['app']['App']['SaveClip']();
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SetConfig(arg1) {
  return window['go']['app']['App']['SetConfig'](arg1);
}

export function Start() {
  return window['go']['app']['App']['Start']();
}

export function Stop() {
  return window['go']['app']['App']['Stop']();
}
