// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetConfig():Promise<app.Config>;

export function GetDisplays():Promise<Array<app.DisplayInfo>>;

export function GetEncoders():Promise<Array<app.EncoderInfo>>;

export function GetState():Promise<app.State>;

export function Initialize():Promise<void>;

export function IsRecording():Promise<boolean>;

export function SaveClip():Promise<string>;

export function SetConfig(arg1:app.Config):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
