// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ConvertToMP4(arg1:string):Promise<void>;

export function EmitClipsUpdate():Promise<void>;

export function EstimateMemory(arg1:string,arg2:number):Promise<string>;

export function GetClips():Promise<Array<app.Clip>>;

export function GetConfig():Promise<app.Config>;

export function GetDisplays():Promise<Array<app.DisplayInfo>>;

export function GetEncoders():Promise<Array<app.EncoderInfo>>;

export function GetState():Promise<app.State>;

export function Initialize():Promise<void>;

export function IsRecording():Promise<boolean>;

export function OpenClip(arg1:string):Promise<void>;

export function SaveClip():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetConfig(arg1:app.Config):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
